import { createSlice } from '@reduxjs/toolkit';
import { getApiCall } from '../../helpers/apiCall'


const initialState = {

  groupeDevise: "E",
  loadingDevises: false,
  //it's a list inside object !!!
  deviseList: {}
};


const devise = createSlice({
  name: 'devise',
  initialState,
  reducers: {

    fetchingDevises: (state) => {
      state.loadingDevises = true
    },
    loadDevises: (state, { payload }) => {
      state.deviseList = payload
    },
    fetchingDevisesSuccess: (state) => {
      state.loadingDevises = false
    },
    setGroupeDevise: (state, { payload }) => {
      state.groupeDevise = payload
    },
  }
});


export const { fetchingDevises, loadDevises, fetchingTresoRecap, fetchingDevisesSuccess, setGroupeDevise } = devise.actions;

export const groupeDeviseSelector = state => state.devise.groupeDevise;
export const deviseListSelector = state => state.devise.deviseList.devises;

export default devise.reducer;


export function loadDevisesListAPI(url, requestOptions, history) {

  return async dispatch => {
    dispatch(fetchingDevises());

    try {
      const data = TRESO_DATA;

      dispatch(loadDevises(data));
      dispatch(fetchingDevisesSuccess());

    } catch (error) {
      console.log(error)
    }
  };
}


const TRESO_DATA = {
  "treso": [
      {
          "loanVar": null,
          "couponsBonds": null,
          "rDepoLT": -55400000,
          "bonds": null,
          "repo_total": "",
          "rLoanLT": 6000000,
          "loan_depo_ct": 124500000,
          "termeSpot": null,
          "rDepoCT": -113000000,
          "RpretEmprunt": null,
          "loan_depo_lt": "",
          "rloan_depo_ct": -64000000,
          "solde_theorique_veille": -44936330.140000000107733058030134998262,
          "deltaVeille": null,
          "pretEmprunt": null,
          "solde": -161860045.819999999812115447639371268451,
          "swap_spot": -1671669.01000000000931322574615478515625,
          "rReverse": null,
          "depoLT": null,
          "soldeAemprunter": -37360045.819999999812115447639371268451,
          "total_terme": -8269971.77,
          "amortDepoVar": null,
          "intDepoVar": null,
          "spot": 6417925.10000000030493083613691851496703,
          "nivellementAutre": null,
          "dateTreso": "04/11/2019",
          "amortLoanVar": null,
          "swap_terme": -8269971.77,
          "bondsSomme": null,
          "repo": null,
          "validated": 0,
          "depoCT": 128500000,
          "currency": {
              "currencyName": null,
              "groupeDevise": "U",
              "currencyShortName": "USD",
              "currencyId": 247
          },
          "commentaire": null,
          "depoVar": null,
          "nivellementBO": null,
          "irsReceive": null,
          "solde_reel": null,
          "rRepo": null,
          "total_spot": 4746256.09000000029561761039076372981078,
          "terme": null,
          "reverse": null,
          "rloan_depo_lt": -49400000,
          "loanLT": null,
          "rLoanCT": 49000000,
          "loanCT": -4000000,
          "intLoanVar": null,
          "irsPay": null,
          "irsSomme": null,
          "rbonds": null
      },
      {
          "loanVar": null,
          "couponsBonds": null,
          "rDepoLT": null,
          "bonds": null,
          "repo_total": "",
          "rLoanLT": null,
          "loan_depo_ct": "",
          "termeSpot": null,
          "rDepoCT": null,
          "RpretEmprunt": null,
          "loan_depo_lt": "",
          "rloan_depo_ct": "",
          "solde_theorique_veille": 152933.099999999998544808477163314819336,
          "deltaVeille": null,
          "pretEmprunt": null,
          "solde": 1536017.06999999989784555509686470031738,
          "swap_spot": 2200000,
          "rReverse": null,
          "depoLT": null,
          "soldeAemprunter": 1536017.06999999989784555509686470031738,
          "total_terme": -2200000,
          "amortDepoVar": null,
          "intDepoVar": null,
          "spot": 1383083.96999999989930074661970138549805,
          "nivellementAutre": null,
          "dateTreso": "04/11/2019",
          "amortLoanVar": null,
          "swap_terme": -2200000,
          "bondsSomme": null,
          "repo": null,
          "validated": 0,
          "depoCT": null,
          "currency": {
              "currencyName": null,
              "groupeDevise": "U",
              "currencyShortName": "CAD",
              "currencyId": 921
          },
          "commentaire": null,
          "depoVar": null,
          "nivellementBO": null,
          "irsReceive": null,
          "solde_reel": null,
          "rRepo": null,
          "total_spot": 3583083.96999999989930074661970138549805,
          "terme": null,
          "reverse": null,
          "rloan_depo_lt": "",
          "loanLT": null,
          "rLoanCT": null,
          "loanCT": null,
          "intLoanVar": null,
          "irsPay": null,
          "irsSomme": null,
          "rbonds": null
      },
      {
          "loanVar": null,
          "couponsBonds": null,
          "rDepoLT": null,
          "bonds": null,
          "repo_total": "",
          "rLoanLT": null,
          "loan_depo_ct": "",
          "termeSpot": null,
          "rDepoCT": null,
          "RpretEmprunt": null,
          "loan_depo_lt": "",
          "rloan_depo_ct": "",
          "solde_theorique_veille": -3500,
          "deltaVeille": null,
          "pretEmprunt": null,
          "solde": -3500,
          "swap_spot": null,
          "rReverse": null,
          "depoLT": null,
          "soldeAemprunter": -3500,
          "total_terme": "",
          "amortDepoVar": null,
          "intDepoVar": null,
          "spot": "",
          "nivellementAutre": null,
          "dateTreso": "04/11/2019",
          "amortLoanVar": null,
          "swap_terme": null,
          "bondsSomme": null,
          "repo": null,
          "validated": 0,
          "depoCT": null,
          "currency": {
              "currencyName": null,
              "groupeDevise": "U",
              "currencyShortName": "AED",
              "currencyId": 3924
          },
          "commentaire": null,
          "depoVar": null,
          "nivellementBO": null,
          "irsReceive": null,
          "solde_reel": null,
          "rRepo": null,
          "total_spot": "",
          "terme": null,
          "reverse": null,
          "rloan_depo_lt": "",
          "loanLT": null,
          "rLoanCT": null,
          "loanCT": null,
          "intLoanVar": null,
          "irsPay": null,
          "irsSomme": null,
          "rbonds": null
      },
      {
          "loanVar": null,
          "couponsBonds": null,
          "rDepoLT": -1900000,
          "bonds": null,
          "repo_total": "",
          "rLoanLT": null,
          "loan_depo_ct": "",
          "termeSpot": null,
          "rDepoCT": null,
          "RpretEmprunt": null,
          "loan_depo_lt": 1900000,
          "rloan_depo_ct": "",
          "solde_theorique_veille": 512971.6300000000051113602239638566970825,
          "deltaVeille": null,
          "pretEmprunt": null,
          "solde": -1309744.13999999999532519723288714885711,
          "swap_spot": null,
          "rReverse": null,
          "depoLT": 1900000,
          "soldeAemprunter": 590255.8600000000046748027671128511428825,
          "total_terme": "",
          "amortDepoVar": null,
          "intDepoVar": null,
          "spot": 77284.2299999999995634425431489944458008,
          "nivellementAutre": null,
          "dateTreso": "04/11/2019",
          "amortLoanVar": null,
          "swap_terme": null,
          "bondsSomme": null,
          "repo": null,
          "validated": 0,
          "depoCT": null,
          "currency": {
              "currencyName": null,
              "groupeDevise": "U",
              "currencyShortName": "GBP",
              "currencyId": 129
          },
          "commentaire": null,
          "depoVar": null,
          "nivellementBO": null,
          "irsReceive": null,
          "solde_reel": null,
          "rRepo": null,
          "total_spot": 77284.2299999999995634425431489944458008,
          "terme": null,
          "reverse": null,
          "rloan_depo_lt": -1900000,
          "loanLT": null,
          "rLoanCT": null,
          "loanCT": null,
          "intLoanVar": null,
          "irsPay": null,
          "irsSomme": null,
          "rbonds": null
      },
      {
          "loanVar": null,
          "couponsBonds": null,
          "rDepoLT": null,
          "bonds": null,
          "repo_total": "",
          "rLoanLT": null,
          "loan_depo_ct": "",
          "termeSpot": null,
          "rDepoCT": null,
          "RpretEmprunt": null,
          "loan_depo_lt": "",
          "rloan_depo_ct": "",
          "solde_theorique_veille": "",
          "deltaVeille": null,
          "pretEmprunt": null,
          "solde": -5510.98999999999978172127157449722290039,
          "swap_spot": null,
          "rReverse": null,
          "depoLT": null,
          "soldeAemprunter": -5510.98999999999978172127157449722290039,
          "total_terme": "",
          "amortDepoVar": null,
          "intDepoVar": null,
          "spot": -5510.98999999999978172127157449722290039,
          "nivellementAutre": null,
          "dateTreso": "04/11/2019",
          "amortLoanVar": null,
          "swap_terme": null,
          "bondsSomme": null,
          "repo": null,
          "validated": 0,
          "depoCT": null,
          "currency": {
              "currencyName": null,
              "groupeDevise": "U",
              "currencyShortName": "KWD",
              "currencyId": 3811
          },
          "commentaire": null,
          "depoVar": null,
          "nivellementBO": null,
          "irsReceive": null,
          "solde_reel": null,
          "rRepo": null,
          "total_spot": -5510.98999999999978172127157449722290039,
          "terme": null,
          "reverse": null,
          "rloan_depo_lt": "",
          "loanLT": null,
          "rLoanCT": null,
          "loanCT": null,
          "intLoanVar": null,
          "irsPay": null,
          "irsSomme": null,
          "rbonds": null
      },
      {
          "loanVar": null,
          "couponsBonds": null,
          "rDepoLT": null,
          "bonds": null,
          "repo_total": "",
          "rLoanLT": null,
          "loan_depo_ct": "",
          "termeSpot": null,
          "rDepoCT": null,
          "RpretEmprunt": null,
          "loan_depo_lt": "",
          "rloan_depo_ct": "",
          "solde_theorique_veille": "",
          "deltaVeille": null,
          "pretEmprunt": null,
          "solde": 4690.8800000000001091393642127513885498,
          "swap_spot": null,
          "rReverse": null,
          "depoLT": null,
          "soldeAemprunter": 4690.8800000000001091393642127513885498,
          "total_terme": "",
          "amortDepoVar": null,
          "intDepoVar": null,
          "spot": 4690.8800000000001091393642127513885498,
          "nivellementAutre": null,
          "dateTreso": "04/11/2019",
          "amortLoanVar": null,
          "swap_terme": null,
          "bondsSomme": null,
          "repo": null,
          "validated": 0,
          "depoCT": null,
          "currency": {
              "currencyName": null,
              "groupeDevise": "U",
              "currencyShortName": "CNY",
              "currencyId": 21766
          },
          "commentaire": null,
          "depoVar": null,
          "nivellementBO": null,
          "irsReceive": null,
          "solde_reel": null,
          "rRepo": null,
          "total_spot": 4690.8800000000001091393642127513885498,
          "terme": null,
          "reverse": null,
          "rloan_depo_lt": "",
          "loanLT": null,
          "rLoanCT": null,
          "loanCT": null,
          "intLoanVar": null,
          "irsPay": null,
          "irsSomme": null,
          "rbonds": null
      },
      {
          "loanVar": null,
          "couponsBonds": null,
          "rDepoLT": null,
          "bonds": null,
          "repo_total": "",
          "rLoanLT": null,
          "loan_depo_ct": "",
          "termeSpot": null,
          "rDepoCT": null,
          "RpretEmprunt": null,
          "loan_depo_lt": "",
          "rloan_depo_ct": "",
          "solde_theorique_veille": "",
          "deltaVeille": null,
          "pretEmprunt": null,
          "solde": -1005360,
          "swap_spot": null,
          "rReverse": null,
          "depoLT": null,
          "soldeAemprunter": -1005360,
          "total_terme": "",
          "amortDepoVar": null,
          "intDepoVar": null,
          "spot": -1005360,
          "nivellementAutre": null,
          "dateTreso": "04/11/2019",
          "amortLoanVar": null,
          "swap_terme": null,
          "bondsSomme": null,
          "repo": null,
          "validated": 0,
          "depoCT": null,
          "currency": {
              "currencyName": null,
              "groupeDevise": "U",
              "currencyShortName": "JPY",
              "currencyId": 270
          },
          "commentaire": null,
          "depoVar": null,
          "nivellementBO": null,
          "irsReceive": null,
          "solde_reel": null,
          "rRepo": null,
          "total_spot": -1005360,
          "terme": null,
          "reverse": null,
          "rloan_depo_lt": "",
          "loanLT": null,
          "rLoanCT": null,
          "loanCT": null,
          "intLoanVar": null,
          "irsPay": null,
          "irsSomme": null,
          "rbonds": null
      },
      {
          "loanVar": null,
          "couponsBonds": null,
          "rDepoLT": null,
          "bonds": null,
          "repo_total": "",
          "rLoanLT": null,
          "loan_depo_ct": "",
          "termeSpot": null,
          "rDepoCT": null,
          "RpretEmprunt": null,
          "loan_depo_lt": "",
          "rloan_depo_ct": "",
          "solde_theorique_veille": -292870,
          "deltaVeille": null,
          "pretEmprunt": null,
          "solde": -292870,
          "swap_spot": null,
          "rReverse": null,
          "depoLT": null,
          "soldeAemprunter": -292870,
          "total_terme": "",
          "amortDepoVar": null,
          "intDepoVar": null,
          "spot": "",
          "nivellementAutre": null,
          "dateTreso": "04/11/2019",
          "amortLoanVar": null,
          "swap_terme": null,
          "bondsSomme": null,
          "repo": null,
          "validated": 0,
          "depoCT": null,
          "currency": {
              "currencyName": null,
              "groupeDevise": "U",
              "currencyShortName": "SAR",
              "currencyId": 3866
          },
          "commentaire": null,
          "depoVar": null,
          "nivellementBO": null,
          "irsReceive": null,
          "solde_reel": null,
          "rRepo": null,
          "total_spot": "",
          "terme": null,
          "reverse": null,
          "rloan_depo_lt": "",
          "loanLT": null,
          "rLoanCT": null,
          "loanCT": null,
          "intLoanVar": null,
          "irsPay": null,
          "irsSomme": null,
          "rbonds": null
      }
  ]
}